SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3 # seconds

SHOT_RADIUS = 5

LEADERBOARD_PATH = "src/leaderboard/leaderboard.json"
MAX_ENTRIES = 40

BG_COLOR = (10, 10, 10) #for the final menu
TITLE_COLOR = (150, 200, 255) #for the final menu